### ISSUE TITLE
Unable to install using cocoapods

### ISSUE THREAD

**Issue by jpaas** [robertBojor/RBHUD#1]
Something wrong with the podspec?

```
[!] Unable to satisfy the following requirements:

- `RBHUD (= 0.1.0)` required by `Podfile`
- `RBHUD (= 0.1.0)` required by `Podfile`
- `RBHUD (= 0.1.0)` required by `Podfile`
```

**Comment by robertBojor** [comment]
Don't know whyCocoaPids has that version, but the podspec is at version 0.0.2. Will check as soon as I'm in front of a computer.

**Comment by robertBojor** [comment]
Hey jpaas, 

Try installing it using the :git extra option in the Podfile... Really don't know why CocoaPods went to 0.1.0 when I've changed the version a long time ago.

I'll update the README file now. Let me know if it works for you, so I can close this issue.

Thanks.
